In [2]:
import numpy as np

In [388]:
#  1d 
arr1 = np.array(np.random.randint(1,100,10))
arr1

array([65, 93, 80, 38, 10, 14, 46, 74, 42, 35])

In [389]:
#  2d
arr2 = np.array(np.random.randint(1,100,10)).reshape(2,5)
arr2

array([[85, 49, 86, 65, 83],
       [18,  4, 67, 24, 25]])

In [390]:
arr3  = np.array(np.random.randint(1,100,20)).reshape(2,5,2)


In [391]:

print(arr2.dtype)
print(arr1.dtype)
print(arr3.dtype)

int32
int32
int32


In [392]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(10,)
(2, 5)
(2, 5, 2)


In [393]:
arr1.ndim

1

In [394]:
arr2.ndim

2

In [395]:
arr3.ndim


3

In [396]:
arra1 = np.zeros(12)
arr1

array([65, 93, 80, 38, 10, 14, 46, 74, 42, 35])

In [397]:
np.ones(12).reshape(2,6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [398]:
Maths  = np.random.randint(1,100,20)
Maths

array([89, 73, 14, 23, 57, 20, 80, 71,  7, 99, 32, 91, 19, 35, 55, 75, 46,
       13, 52, 23])

In [399]:
asc = np.sort(Maths)
asc

array([ 7, 13, 14, 19, 20, 23, 23, 32, 35, 46, 52, 55, 57, 71, 73, 75, 80,
       89, 91, 99])

In [400]:
np.flip(asc)

array([99, 91, 89, 80, 75, 73, 71, 57, 55, 52, 46, 35, 32, 23, 23, 20, 19,
       14, 13,  7])

In [401]:
dcopy = np.copy(asc)

In [402]:
dcopy[2] = 10

In [403]:
dcopy

array([ 7, 13, 10, 19, 20, 23, 23, 32, 35, 46, 52, 55, 57, 71, 73, 75, 80,
       89, 91, 99])

In [404]:
asc

array([ 7, 13, 14, 19, 20, 23, 23, 32, 35, 46, 52, 55, 57, 71, 73, 75, 80,
       89, 91, 99])

In [405]:
idt = np.eye(5)
idt.flatten()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [406]:
idt.ravel()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [407]:
td = np.random.randint(1,20,9).reshape(3,3)

In [408]:
td  = np.append(td , [[1,2,3]], axis = 0)


In [409]:
td

array([[19,  4,  9],
       [14,  1, 11],
       [18,  5, 12],
       [ 1,  2,  3]])

In [410]:
td = np.append(td,[[10],[1],[12],[14]], axis = 1)

In [411]:
td

array([[19,  4,  9, 10],
       [14,  1, 11,  1],
       [18,  5, 12, 12],
       [ 1,  2,  3, 14]])

In [412]:
np.hsplit(td,2)

[array([[19,  4],
        [14,  1],
        [18,  5],
        [ 1,  2]]),
 array([[ 9, 10],
        [11,  1],
        [12, 12],
        [ 3, 14]])]

In [413]:
np.vsplit(td,2)

[array([[19,  4,  9, 10],
        [14,  1, 11,  1]]),
 array([[18,  5, 12, 12],
        [ 1,  2,  3, 14]])]

In [414]:
np.split(td,2,axis = 0)

[array([[19,  4,  9, 10],
        [14,  1, 11,  1]]),
 array([[18,  5, 12, 12],
        [ 1,  2,  3, 14]])]

In [415]:
fbf  = np.arange(16).reshape(4,4)
fbf+4

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [416]:
thtn = np.random.uniform(1,100,10)

In [417]:
np.round(thtn,2)

array([64.49, 25.91, 89.7 , 75.08, 99.89, 85.74, 66.78, 86.19, 67.67,
       38.85])

In [418]:
np.ceil(thtn)

array([ 65.,  26.,  90.,  76., 100.,  86.,  67.,  87.,  68.,  39.])

In [419]:
np.floor(thtn)

array([64., 25., 89., 75., 99., 85., 66., 86., 67., 38.])

In [420]:
fthn = np.random.randint(1,100,25).reshape(5,5)

In [421]:
fthn

array([[77, 90, 50, 69, 45],
       [10, 81, 78, 56, 88],
       [34, 79, 40, 44, 64],
       [ 1, 12, 61, 88, 20],
       [10, 27, 79, 64, 37]])

In [422]:
np.min(fthn,axis= 0)

array([ 1, 12, 40, 44, 20])

In [423]:
fthn.max(axis=0)

array([77, 90, 79, 88, 88])

In [424]:
fthn.std(axis = 0)

array([27.57245002, 31.84587885, 15.31796331, 14.59314908, 23.37006632])

In [425]:
fthn.var(axis = 0)

array([ 760.24, 1014.16,  234.64,  212.96,  546.16])

In [426]:
fthn = np.zeros(10)
fthn[5] = 6
fthn

array([0., 0., 0., 0., 0., 6., 0., 0., 0., 0.])

In [427]:
sthn = np.arange(100,151)
sthn

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [428]:
np.flip(sthn)

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [429]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [430]:
nithn = np.array([1,0,2,0,0,4,0,8])
np.nonzero(nithn)

(array([0, 2, 5, 7], dtype=int32),)

In [431]:
np.where(nithn == 2)

(array([2], dtype=int32),)

In [432]:
twt = np.ones(100).reshape(10,10)
twt[1:9,1:9]=0
twt

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [433]:
twt1 = np.zeros(64).reshape(8,8)
twt1[::2,1::2]=1
twt1[1::2,::2]=1
twt1

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [434]:
mat1 = np.random.randint(1,100,9).reshape(3,3)
mat2 = np.random.randint(1,100,9).reshape(3,3)
print(mat1)
print(mat2)

[[25 42 47]
 [33 32 73]
 [38 44 20]]
[[42 36 57]
 [83 79 46]
 [69 69 42]]


In [435]:
mat1+mat2

array([[ 67,  78, 104],
       [116, 111, 119],
       [107, 113,  62]])

In [436]:
np.dot(mat1,mat2)

array([[7779, 7461, 5331],
       [9079, 8753, 6419],
       [6628, 6224, 5030]])

In [437]:
np.mean(mat1)

39.333333333333336

In [438]:
np.median(mat1)

38.0

In [439]:
np.sin(mat1)

array([[-0.13235175, -0.91652155,  0.12357312],
       [ 0.99991186,  0.55142668, -0.67677196],
       [ 0.29636858,  0.01770193,  0.91294525]])

In [440]:
np.log(mat1)

array([[3.21887582, 3.73766962, 3.8501476 ],
       [3.49650756, 3.4657359 , 4.29045944],
       [3.63758616, 3.78418963, 2.99573227]])

In [441]:
import pandas as pd

In [442]:
cl = "ProductId ProductName ProductPrice"
dl = cl.split()
index = "A B C D E".split()
tto = pd.DataFrame(np.random.randint(1,100,size=(5,3)), columns=dl,index = index)


In [443]:
tto

ProductId  ProductName  ProductPrice
A          8           71            56
B         65           66            24
C         60           54             6
D         91           51            25
E         34           26            18

In [444]:
tto[["ProductId"]]

ProductId
A          8
B         65
C         60
D         91
E         34

In [445]:
tto.loc[('A','ProductName')]

71

In [446]:
tto.iloc[0]["ProductName"]

71

In [447]:
tto.iloc[2:]

ProductId  ProductName  ProductPrice
C         60           54             6
D         91           51            25
E         34           26            18

In [448]:
tto.iloc[1:4][["ProductId","ProductName"]]

ProductId  ProductName
B         65           66
C         60           54
D         91           51

In [449]:
tto[0:3]["ProductPrice"]

A    56
B    24
C     6
Name: ProductPrice, dtype: int32

In [450]:

idx = np.arange(100,151)
ttt = pd.DataFrame( np.random.randint(1,100, size = (51,3)), columns="Python DataScience Biology".split(),index=idx)

In [451]:
ttt

Python  DataScience  Biology
100      39           24       71
101      58           72       39
102      31           97       67
103      66           50       50
104      91           64       29
105      89           61       62
106      31           45       19
107      97           40       94
108      65           99       47
109      27           11        9
110      85           80       79
111      10           23       49
112      26           37        9
113      90           78       51
114      34           77       90
115      65           78       66
116      86           86       38
117      85           23       68
118      88           79       17
119      28           57        2
120      47           73       90
121      56           36        4
122      61           92       30
123      29           63       88
124      43           25       64
125      78           10       43
126      23           57       45
127      17           70       99
128       9           76       96
129      65           38       79
130      71           42       12
131      64           23       29
132      39           76       53
133       4           94       89
134      86           78       33
135      47           49       13
136      34           74        9
137      39           91       21
138      61           47       53
139      33           60       91
140      11           58       53
141      50            7       84
142      14           24       11
143      71           46       62
144      90           53       95
145      53           60       62
146      26           85       40
147      93           47       22
148      12           93        6
149      76           36       52
150      56           63       24

In [452]:
ttt['Python'] = ttt['Python'].where(ttt['Python']>=40,41)

In [453]:
ttt

Python  DataScience  Biology
100      41           24       71
101      58           72       39
102      41           97       67
103      66           50       50
104      91           64       29
105      89           61       62
106      41           45       19
107      97           40       94
108      65           99       47
109      41           11        9
110      85           80       79
111      41           23       49
112      41           37        9
113      90           78       51
114      41           77       90
115      65           78       66
116      86           86       38
117      85           23       68
118      88           79       17
119      41           57        2
120      47           73       90
121      56           36        4
122      61           92       30
123      41           63       88
124      43           25       64
125      78           10       43
126      41           57       45
127      41           70       99
128      41           76       96
129      65           38       79
130      71           42       12
131      64           23       29
132      41           76       53
133      41           94       89
134      86           78       33
135      47           49       13
136      41           74        9
137      41           91       21
138      61           47       53
139      41           60       91
140      41           58       53
141      50            7       84
142      41           24       11
143      71           46       62
144      90           53       95
145      53           60       62
146      41           85       40
147      93           47       22
148      41           93        6
149      76           36       52
150      56           63       24

In [454]:
ttt = ttt+20
ttt.where(ttt<100,100)

Python  DataScience  Biology
100      61           44       91
101      78           92       59
102      61          100       87
103      86           70       70
104     100           84       49
105     100           81       82
106      61           65       39
107     100           60      100
108      85          100       67
109      61           31       29
110     100          100       99
111      61           43       69
112      61           57       29
113     100           98       71
114      61           97      100
115      85           98       86
116     100          100       58
117     100           43       88
118     100           99       37
119      61           77       22
120      67           93      100
121      76           56       24
122      81          100       50
123      61           83      100
124      63           45       84
125      98           30       63
126      61           77       65
127      61           90      100
128      61           96      100
129      85           58       99
130      91           62       32
131      84           43       49
132      61           96       73
133      61          100      100
134     100           98       53
135      67           69       33
136      61           94       29
137      61          100       41
138      81           67       73
139      61           80      100
140      61           78       73
141      70           27      100
142      61           44       31
143      91           66       82
144     100           73      100
145      73           80       82
146      61          100       60
147     100           67       42
148      61          100       26
149      96           56       72
150      76           83       44

In [455]:
ttt[(ttt['Python'] > 50) & (ttt['DataScience'] > 60)]


Python  DataScience  Biology
101      78           92       59
102      61          117       87
103      86           70       70
104     111           84       49
105     109           81       82
106      61           65       39
108      85          119       67
110     105          100       99
113     110           98       71
114      61           97      110
115      85           98       86
116     106          106       58
118     108           99       37
119      61           77       22
120      67           93      110
122      81          112       50
123      61           83      108
126      61           77       65
127      61           90      119
128      61           96      116
130      91           62       32
132      61           96       73
133      61          114      109
134     106           98       53
135      67           69       33
136      61           94       29
137      61          111       41
138      81           67       73
139      61           80      111
140      61           78       73
143      91           66       82
144     110           73      115
145      73           80       82
146      61          105       60
147     113           67       42
148      61          113       26
150      76           83       44

In [456]:
ttt.loc[155] = (100,100,100)

In [457]:
ttt['Total'] = ttt['Python']+ttt['DataScience']+ttt['Biology']

In [458]:
ttt['Percentage'] = ttt['Total']/3

In [459]:
ttt

Python  DataScience  Biology  Total  Percentage
100      61           44       91    196   65.333333
101      78           92       59    229   76.333333
102      61          117       87    265   88.333333
103      86           70       70    226   75.333333
104     111           84       49    244   81.333333
105     109           81       82    272   90.666667
106      61           65       39    165   55.000000
107     117           60      114    291   97.000000
108      85          119       67    271   90.333333
109      61           31       29    121   40.333333
110     105          100       99    304  101.333333
111      61           43       69    173   57.666667
112      61           57       29    147   49.000000
113     110           98       71    279   93.000000
114      61           97      110    268   89.333333
115      85           98       86    269   89.666667
116     106          106       58    270   90.000000
117     105           43       88    236   78.666667
118     108           99       37    244   81.333333
119      61           77       22    160   53.333333
120      67           93      110    270   90.000000
121      76           56       24    156   52.000000
122      81          112       50    243   81.000000
123      61           83      108    252   84.000000
124      63           45       84    192   64.000000
125      98           30       63    191   63.666667
126      61           77       65    203   67.666667
127      61           90      119    270   90.000000
128      61           96      116    273   91.000000
129      85           58       99    242   80.666667
130      91           62       32    185   61.666667
131      84           43       49    176   58.666667
132      61           96       73    230   76.666667
133      61          114      109    284   94.666667
134     106           98       53    257   85.666667
135      67           69       33    169   56.333333
136      61           94       29    184   61.333333
137      61          111       41    213   71.000000
138      81           67       73    221   73.666667
139      61           80      111    252   84.000000
140      61           78       73    212   70.666667
141      70           27      104    201   67.000000
142      61           44       31    136   45.333333
143      91           66       82    239   79.666667
144     110           73      115    298   99.333333
145      73           80       82    235   78.333333
146      61          105       60    226   75.333333
147     113           67       42    222   74.000000
148      61          113       26    200   66.666667
149      96           56       72    224   74.666667
150      76           83       44    203   67.666667
155     100          100      100    300  100.000000

In [460]:
ttt['Percentage'] = np.ceil(ttt['Percentage'])


In [461]:
ttt['Status'] = np.where(ttt['Percentage']>40, 'Pass','Fail')

In [462]:
ttt

Python  DataScience  Biology  Total  Percentage Status
100      61           44       91    196        66.0   Pass
101      78           92       59    229        77.0   Pass
102      61          117       87    265        89.0   Pass
103      86           70       70    226        76.0   Pass
104     111           84       49    244        82.0   Pass
105     109           81       82    272        91.0   Pass
106      61           65       39    165        55.0   Pass
107     117           60      114    291        97.0   Pass
108      85          119       67    271        91.0   Pass
109      61           31       29    121        41.0   Pass
110     105          100       99    304       102.0   Pass
111      61           43       69    173        58.0   Pass
112      61           57       29    147        49.0   Pass
113     110           98       71    279        93.0   Pass
114      61           97      110    268        90.0   Pass
115      85           98       86    269        90.0   Pass
116     106          106       58    270        90.0   Pass
117     105           43       88    236        79.0   Pass
118     108           99       37    244        82.0   Pass
119      61           77       22    160        54.0   Pass
120      67           93      110    270        90.0   Pass
121      76           56       24    156        52.0   Pass
122      81          112       50    243        81.0   Pass
123      61           83      108    252        84.0   Pass
124      63           45       84    192        64.0   Pass
125      98           30       63    191        64.0   Pass
126      61           77       65    203        68.0   Pass
127      61           90      119    270        90.0   Pass
128      61           96      116    273        91.0   Pass
129      85           58       99    242        81.0   Pass
130      91           62       32    185        62.0   Pass
131      84           43       49    176        59.0   Pass
132      61           96       73    230        77.0   Pass
133      61          114      109    284        95.0   Pass
134     106           98       53    257        86.0   Pass
135      67           69       33    169        57.0   Pass
136      61           94       29    184        62.0   Pass
137      61          111       41    213        71.0   Pass
138      81           67       73    221        74.0   Pass
139      61           80      111    252        84.0   Pass
140      61           78       73    212        71.0   Pass
141      70           27      104    201        67.0   Pass
142      61           44       31    136        46.0   Pass
143      91           66       82    239        80.0   Pass
144     110           73      115    298       100.0   Pass
145      73           80       82    235        79.0   Pass
146      61          105       60    226        76.0   Pass
147     113           67       42    222        74.0   Pass
148      61          113       26    200        67.0   Pass
149      96           56       72    224        75.0   Pass
150      76           83       44    203        68.0   Pass
155     100          100      100    300       100.0   Pass

In [463]:
ttt.sum()

Python                                                      4114
DataScience                                                 4047
Biology                                                     3628
Total                                                      11789
Percentage                                                3947.0
Status         PassPassPassPassPassPassPassPassPassPassPassPa...
dtype: object

In [464]:
ttt.max()

Python           117
DataScience      119
Biology          119
Total            304
Percentage     102.0
Status          Pass
dtype: object

In [465]:
ttt.min()

Python           61
DataScience      27
Biology          22
Total           121
Percentage     41.0
Status         Pass
dtype: object

In [466]:
ttt.std()

<ipython-input-466-d44d9ab196e3>:1: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  ttt.std()


Python         19.377219
DataScience    24.784341
Biology        29.416959
Total          45.306077
Percentage     15.072712
dtype: float64

In [467]:
ttt.var()

<ipython-input-467-684170ef8824>:1: FutureWarning: The default value of numeric_only in DataFrame.var is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  ttt.var()


Python          375.476621
DataScience     614.263575
Biology         865.357466
Total          2052.640649
Percentage      227.186652
dtype: float64

In [468]:
ttt.describe()

Python  DataScience     Biology       Total  Percentage
count   52.000000    52.000000   52.000000   52.000000   52.000000
mean    79.115385    77.826923   69.769231  226.711538   75.903846
std     19.377219    24.784341   29.416959   45.306077   15.072712
min     61.000000    27.000000   22.000000  121.000000   41.000000
25%     61.000000    59.500000   43.500000  195.000000   65.500000
50%     74.500000    80.000000   70.500000  229.500000   77.000000
75%     96.500000    98.000000   93.000000  268.250000   90.000000
max    117.000000   119.000000  119.000000  304.000000  102.000000

In [469]:
dic = tto.to_dict(orient =  'list')
dic

{'ProductId': [8, 65, 60, 91, 34],
 'ProductName': [71, 66, 54, 51, 26],
 'ProductPrice': [56, 24, 6, 25, 18]}

In [470]:
new = pd.DataFrame(dic)

In [471]:
new  ['ProductPrice']= new['ProductPrice']+500

In [472]:
new

ProductId  ProductName  ProductPrice
0          8           71           556
1         65           66           524
2         60           54           506
3         91           51           525
4         34           26           518

In [473]:
sd= [19, 96, 76, 49, 92]

pd.Series(sd,index = ("A B C D E").split())

A    19
B    96
C    76
D    49
E    92
dtype: int64

In [474]:
sal  = pd.read_csv("Salaries.csv")

<ipython-input-474-41c849ca0860>:1: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  sal  = pd.read_csv("Salaries.csv")


In [475]:
sal

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle       BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY     167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)     155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)     212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC       77916.0   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)      134401.6   
...                                                ...           ...   
148649                                       Custodian          0.00   
148650                                    Not provided  Not Provided   
148651                                    Not provided  Not Provided   
148652                                    Not provided  Not Provided   
148653                      Counselor, Log Cabin Ranch          0.00   

         OvertimePay      OtherPay      Benefits   TotalPay  TotalPayBenefits  \
0                0.0     400184.25           NaN  567595.43         567595.43   
1          245131.88     137811.38           NaN  538909.28         538909.28   
2          106088.18       16452.6           NaN  335279.91         335279.91   
3           56120.71      198306.9           NaN  332343.61         332343.61   
4             9737.0     182234.59           NaN  326373.19         326373.19   
...              ...           ...           ...        ...               ...   
148649          0.00          0.00          0.00       0.00              0.00   
148650  Not Provided  Not Provided  Not Provided       0.00              0.00   
148651  Not Provided  Not Provided  Not Provided       0.00              0.00   
148652  Not Provided  Not Provided  Not Provided       0.00              0.00   
148653          0.00       -618.13          0.00    -618.13           -618.13   

        Year  Notes         Agency Status  
0       2011    NaN  San Francisco    NaN  
1       2011    NaN  San Francisco    NaN  
2       2011    NaN  San Francisco    NaN  
3       2011    NaN  San Francisco    NaN  
4       2011    NaN  San Francisco    NaN  
...      ...    ...            ...    ...  
148649  2014    NaN  San Francisco     PT  
148650  2014    NaN  San Francisco    NaN  
148651  2014    NaN  San Francisco    NaN  
148652  2014    NaN  San Francisco    NaN  
148653  2014    NaN  San Francisco     PT  

[148654 rows x 13 columns]

In [476]:
sal = sal.replace(to_replace = 'Not Provided',value = np.nan)
sal = sal.replace(to_replace = 'Not provided',value = np.nan)
sal = sal.fillna(1)
sal

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651                  1   
148651  148652                  1   
148652  148653                  1   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay OvertimePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18         0.0   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   245131.88   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   106088.18   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC    77916.0    56120.71   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   134401.6      9737.0   
...                                                ...        ...         ...   
148649                                       Custodian       0.00        0.00   
148650                                               1          1           1   
148651                                               1          1           1   
148652                                               1          1           1   
148653                      Counselor, Log Cabin Ranch       0.00        0.00   

         OtherPay Benefits   TotalPay  TotalPayBenefits  Year  Notes  \
0       400184.25        1  567595.43         567595.43  2011    1.0   
1       137811.38        1  538909.28         538909.28  2011    1.0   
2         16452.6        1  335279.91         335279.91  2011    1.0   
3        198306.9        1  332343.61         332343.61  2011    1.0   
4       182234.59        1  326373.19         326373.19  2011    1.0   
...           ...      ...        ...               ...   ...    ...   
148649       0.00     0.00       0.00              0.00  2014    1.0   
148650          1        1       0.00              0.00  2014    1.0   
148651          1        1       0.00              0.00  2014    1.0   
148652          1        1       0.00              0.00  2014    1.0   
148653    -618.13     0.00    -618.13           -618.13  2014    1.0   

               Agency Status  
0       San Francisco      1  
1       San Francisco      1  
2       San Francisco      1  
3       San Francisco      1  
4       San Francisco      1  
...               ...    ...  
148649  San Francisco     PT  
148650  San Francisco      1  
148651  San Francisco      1  
148652  San Francisco      1  
148653  San Francisco     PT  

[148654 rows x 13 columns]

In [477]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148654 non-null  object 
 4   OvertimePay       148654 non-null  object 
 5   OtherPay          148654 non-null  object 
 6   Benefits          148654 non-null  object 
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             148654 non-null  float64
 11  Agency            148654 non-null  object 
 12  Status            148654 non-null  object 
dtypes: float64(3), int64(2), object(8)
memory usage: 10.2+ MB


In [478]:
sal['BasePay'] = sal['BasePay'].astype('float')
sal['OvertimePay'] = sal['OvertimePay'].astype('float')
sal['OvertimePay'] = sal['OvertimePay'].astype('float')
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148654 non-null  float64
 4   OvertimePay       148654 non-null  float64
 5   OtherPay          148654 non-null  object 
 6   Benefits          148654 non-null  object 
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             148654 non-null  float64
 11  Agency            148654 non-null  object 
 12  Status            148654 non-null  object 
dtypes: float64(5), int64(2), object(6)
memory usage: 11.3+ MB


In [479]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25        1  567595.43         567595.43   
1  155966.02    245131.88  137811.38        1  538909.28         538909.28   
2  212739.13    106088.18    16452.6        1  335279.91         335279.91   
3   77916.00     56120.71   198306.9        1  332343.61         332343.61   
4  134401.60      9737.00  182234.59        1  326373.19         326373.19   

   Year  Notes         Agency Status  
0  2011    1.0  San Francisco      1  
1  2011    1.0  San Francisco      1  
2  2011    1.0  San Francisco      1  
3  2011    1.0  San Francisco      1  
4  2011    1.0  San Francisco      1

In [480]:
sal.tail()

Id   EmployeeName                    JobTitle  BasePay  \
148649  148650  Roy I Tillery                   Custodian      0.0   
148650  148651              1                           1      1.0   
148651  148652              1                           1      1.0   
148652  148653              1                           1      1.0   
148653  148654      Joe Lopez  Counselor, Log Cabin Ranch      0.0   

        OvertimePay OtherPay Benefits  TotalPay  TotalPayBenefits  Year  \
148649          0.0     0.00     0.00      0.00              0.00  2014   
148650          1.0        1        1      0.00              0.00  2014   
148651          1.0        1        1      0.00              0.00  2014   
148652          1.0        1        1      0.00              0.00  2014   
148653          0.0  -618.13     0.00   -618.13           -618.13  2014   

        Notes         Agency Status  
148649    1.0  San Francisco     PT  
148650    1.0  San Francisco      1  
148651    1.0  San Francisco      1  
148652    1.0  San Francisco      1  
148653    1.0  San Francisco     PT

In [481]:
sal['BasePay'].mean()

66053.73338483997

In [482]:
sal['OvertimePay'].max()

245131.88

In [483]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [484]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [485]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].max()]['EmployeeName']


0    NATHANIEL FORD
Name: EmployeeName, dtype: object

In [486]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].min()]


Id EmployeeName                    JobTitle  BasePay  OvertimePay  \
148653  148654    Joe Lopez  Counselor, Log Cabin Ranch      0.0          0.0   

       OtherPay Benefits  TotalPay  TotalPayBenefits  Year  Notes  \
148653  -618.13     0.00   -618.13           -618.13  2014    1.0   

               Agency Status  
148653  San Francisco     PT

In [487]:
sal.groupby('Year').mean()['BasePay']

<ipython-input-487-a42aa5aba483>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  sal.groupby('Year').mean()['BasePay']


Year
2011    63595.956517
2012    65436.406857
2013    68509.848243
2014    66557.437855
Name: BasePay, dtype: float64

In [488]:
sal['JobTitle'].nunique()

2159

In [489]:
sal['JobTitle'].value_counts().head()

Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: JobTitle, dtype: int64

In [490]:
sum(sal[sal['Year'] == 2013]['JobTitle'].value_counts() == 1)



202

In [491]:
sal['JobTitle'].str.contains('Chief').sum()

423

In [492]:
arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [493]:
arr = np.random.randint(0,8,size = (3,3))
arr

array([[1, 4, 7],
       [6, 4, 2],
       [7, 0, 2]])

In [494]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [495]:
np.random.rand(1)

array([0.1436197])

In [496]:
arr = np.random.rand(25)
arr

array([0.64654463, 0.00150734, 0.52914464, 0.92587982, 0.21001378,
       0.40020355, 0.25101307, 0.58764654, 0.45461802, 0.87020815,
       0.926538  , 0.69318919, 0.3244032 , 0.51308627, 0.17614667,
       0.11765358, 0.5639795 , 0.18641879, 0.99915866, 0.19296364,
       0.15540397, 0.25074599, 0.52886088, 0.54763895, 0.9094994 ])

In [497]:
arr = np.linspace(0.01,1,100).reshape(10,10)
arr

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [498]:
arr = np.linspace(0,1,20)
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [499]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [500]:
arr[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [501]:
arr[3,4]

20

In [502]:
arr[2:,1:2]

array([[12],
       [17],
       [22]])

In [503]:
arr.sum(axis = 0)

array([55, 60, 65, 70, 75])

In [504]:
arr.std(axis = 1)

array([1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356])

In [505]:
arr.min(axis = 1)

array([ 1,  6, 11, 16, 21])

In [506]:
arr.max(axis = 1)

array([ 5, 10, 15, 20, 25])

In [507]:
arr.var(axis = 1)

array([2., 2., 2., 2., 2.])

In [508]:
a = np.zeros(4).reshape(2,2)

In [509]:
a[0,:] = np.nan

In [510]:
a

array([[nan, nan],
       [ 0.,  0.]])

In [511]:
np.ones(12).reshape(2,2,3)

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [512]:
arr = np.random.randint(1,100,10)
arr

array([93,  6, 88, 16, 21, 53, 85, 28, 87, 81])

In [513]:
a= np.sort(arr)

In [514]:
np.flip(a)

array([93, 88, 87, 85, 81, 53, 28, 21, 16,  6])

In [515]:
b = np.copy(a)

In [516]:
np.eye(5).ravel()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [517]:
arr = np.random.randint(1,100,size = (3,3))
arr

array([[78, 27, 16],
       [41, 40, 81],
       [84, 59, 47]])

In [518]:
np.append(arr,[[12],[13],[15]],axis = 1)

array([[78, 27, 16, 12],
       [41, 40, 81, 13],
       [84, 59, 47, 15]])

In [519]:
np.split(arr,3,axis = 1)

[array([[78],
        [41],
        [84]]),
 array([[27],
        [40],
        [59]]),
 array([[16],
        [81],
        [47]])]

In [520]:
arr = np.random.randint(1,100,size = (4,4))
arr

array([[ 9, 79,  2, 31],
       [97, 36, 71, 52],
       [25, 15, 17, 69],
       [12, 38, 93, 78]])

In [521]:
arr+4

array([[ 13,  83,   6,  35],
       [101,  40,  75,  56],
       [ 29,  19,  21,  73],
       [ 16,  42,  97,  82]])

In [522]:
arr = np.random.uniform(1,100,size = (3,3))

In [523]:
np.round(arr,2)

array([[67.25, 11.49, 92.93],
       [69.11, 70.76, 82.45],
       [25.75, 91.39, 67.  ]])

In [524]:
np.ceil(arr)

array([[68., 12., 93.],
       [70., 71., 83.],
       [26., 92., 68.]])

In [525]:
np.floor(arr)

array([[67., 11., 92.],
       [69., 70., 82.],
       [25., 91., 67.]])

In [526]:
np.max(arr)

92.92622663018633

In [527]:
one = pd.DataFrame(np.random.randint(1,100,size = (5,2)),columns = "ProductId  ProductPrice".split())
one["Name"] = "Maggie Pasta Lays Kurkure Masala".split()

In [528]:
one

ProductId  ProductPrice     Name
0          6            42   Maggie
1         23            71    Pasta
2         99            81     Lays
3         37            89  Kurkure
4         10            56   Masala

In [529]:

indi = np.arange(100,151)
eig = pd.DataFrame( np.random.randint(1,100, size = (51,3)), columns="Python DataScience Biology".split(),index=idx)

In [530]:
eig

Python  DataScience  Biology
100      22           10       71
101      58            1       22
102      43           72       68
103      82           86       90
104      47           85       35
105      93           88       93
106      78           11       23
107      14           16       61
108      50           93       63
109      86           35       53
110      40           36       49
111      38           97       13
112      46            3       24
113      16           73       40
114      84           46       59
115      53           99       60
116      36           39       91
117      54           25       28
118      14           34       71
119       5           31       76
120      78            1       51
121       7           11       93
122      17           90       76
123       1           28       36
124      18           21       70
125      12           35       80
126      23           14       90
127      46           26       36
128      25           68       40
129      59           32       41
130      62           92       77
131      41           68       16
132      13           45       56
133      96           14       89
134      86           60       64
135       4           67       36
136      67           30       37
137       4           49       15
138      59           92       40
139      39           82       78
140      22           67        8
141      61           19       79
142      49           88       52
143      22           61       39
144       3           47       34
145      85           49       48
146      79           43       71
147      56           97       39
148      79           79        1
149      58           45       99
150      52           65       87

In [531]:
eig['Python'] = eig['Python'].where(eig['Python'] > 40 ,41)

In [532]:
eig = eig+20
eig = eig.where(eig < 100, 100)

In [533]:
eig[(eig["Python"]>50) & (eig["DataScience"]>60)]

Python  DataScience  Biology
102      63           92       88
103     100          100      100
104      67          100       55
105     100          100      100
108      70          100       83
111      61          100       33
113      61           93       60
114     100           66       79
115      73          100       80
122      61          100       96
128      61           88       60
130      82          100       97
131      61           88       36
132      61           65       76
134     100           80       84
135      61           87       56
137      61           69       35
138      79          100       60
139      61          100       98
140      61           87       28
142      69          100       72
143      61           81       59
144      61           67       54
145     100           69       68
146      99           63       91
147      76          100       59
148      99           99       21
149      78           65      100
150      72           85      100

In [534]:
eig['Total'] = eig["Python"]+eig["DataScience"]+eig["Biology"]

In [535]:
eig['Percentage'] = eig["Total"]/3

In [536]:
eig['Status'] = np.where(eig["Percentage"]>40,"Pass","Fail")

In [537]:
a=eig.sum().drop("Status")
a.drop("Grade")

<class 'KeyError'>: "['Grade'] not found in axis"

In [538]:
eig.var()

<ipython-input-538-73c409ba9d9d>:1: FutureWarning: The default value of numeric_only in DataFrame.var is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  eig.var()


Python          234.546667
DataScience     703.863529
Biology         534.254118
Total          1408.810196
Percentage      156.534466
dtype: float64

In [539]:
eig.describe()

Python  DataScience     Biology       Total  Percentage
count   51.000000    51.000000   51.000000   51.000000   51.000000
mean    73.666667    67.764706   72.470588  213.901961   71.300654
std     15.314916    26.530426   23.113938   37.534120   12.511373
min     61.000000    21.000000   21.000000  133.000000   44.333333
25%     61.000000    47.000000   56.000000  188.000000   62.666667
50%     66.000000    66.000000   73.000000  209.000000   69.666667
75%     81.500000    96.000000   96.000000  242.000000   80.666667
max    100.000000   100.000000  100.000000  300.000000  100.000000

In [541]:
import pandas as pd 


In [543]:
s = pd.read_csv('Salaries.csv')

<ipython-input-543-7569c28abd7d>:1: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  s = pd.read_csv('Salaries.csv')


In [545]:
s.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay OvertimePay   OtherPay Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.0  400184.25      NaN  567595.43         567595.43   
1  155966.02   245131.88  137811.38      NaN  538909.28         538909.28   
2  212739.13   106088.18    16452.6      NaN  335279.91         335279.91   
3    77916.0    56120.71   198306.9      NaN  332343.61         332343.61   
4   134401.6      9737.0  182234.59      NaN  326373.19         326373.19   

   Year  Notes         Agency Status  
0  2011    NaN  San Francisco    NaN  
1  2011    NaN  San Francisco    NaN  
2  2011    NaN  San Francisco    NaN  
3  2011    NaN  San Francisco    NaN  
4  2011    NaN  San Francisco    NaN

In [548]:
s.tail()

Id   EmployeeName                    JobTitle       BasePay  \
148649  148650  Roy I Tillery                   Custodian          0.00   
148650  148651   Not provided                Not provided  Not Provided   
148651  148652   Not provided                Not provided  Not Provided   
148652  148653   Not provided                Not provided  Not Provided   
148653  148654      Joe Lopez  Counselor, Log Cabin Ranch          0.00   

         OvertimePay      OtherPay      Benefits  TotalPay  TotalPayBenefits  \
148649          0.00          0.00          0.00      0.00              0.00   
148650  Not Provided  Not Provided  Not Provided      0.00              0.00   
148651  Not Provided  Not Provided  Not Provided      0.00              0.00   
148652  Not Provided  Not Provided  Not Provided      0.00              0.00   
148653          0.00       -618.13          0.00   -618.13           -618.13   

        Year  Notes         Agency Status  
148649  2014    NaN  San Francisco     PT  
148650  2014    NaN  San Francisco    NaN  
148651  2014    NaN  San Francisco    NaN  
148652  2014    NaN  San Francisco    NaN  
148653  2014    NaN  San Francisco     PT

In [549]:
s.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148049 non-null  object 
 4   OvertimePay       148654 non-null  object 
 5   OtherPay          148654 non-null  object 
 6   Benefits          112495 non-null  object 
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            38119 non-null   object 
dtypes: float64(3), int64(2), object(8)
memory usage: 10.2+ MB


In [550]:
s = s.replace(to_replace = "Not Provided", value = np.nan)
s = s.replace(to_replace = "Not provided", value = np.nan)

In [562]:
s["BasePay"].astype('float').mean()

66325.4488404877

In [563]:
s["BasePay"].astype('float').max()

319275.01

In [566]:
s[s['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [584]:
s[s['TotalPayBenefits'] == s['TotalPayBenefits'].max()]

Id    EmployeeName                                        JobTitle  \
0   1  NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   

     BasePay OvertimePay   OtherPay Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.0  400184.25      NaN  567595.43         567595.43   

   Year  Notes         Agency Status  
0  2011    NaN  San Francisco    NaN

In [598]:
s["BasePay"].astype('float').fillna(1)
s.groupby('Year')["BasePay"].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

In [599]:
s['JobTitle'].nunique()

2158

In [629]:
sal[sal['Year'] == 2013]['JobTitle']

72925                    Chief of Police
72926             Chief, Fire Department
72927     Battalion Chief, Fire Suppress
72928                  Asst Med Examiner
72929       Dep Dir for Investments, Ret
                       ...              
110526           PS Aide Health Services
110527                      Senior Clerk
110528                  Police Officer 3
110529                  Police Officer 3
110530                  Police Officer 3
Name: JobTitle, Length: 37606, dtype: object

In [643]:
np.sum(s['JobTitle'].str.contains('Chief'))


423